# Generated by Django 4.0.6 on 2022-07-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_de_tarea', models.CharField(max_length=30)),
                ('responsable_de_uso', models.CharField(max_length=30)),
                
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('responsables', models.CharField(max_length=30)),
                ('dia_de_creacion', models.DateTimeField()),
            ],
        ),
       
    ]
