# Generated by Django 4.0.6 on 2022-07-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0002_herramientas_tareas_alter_familia_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareas',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterField(
            model_name='tareas',
            name='dia_de_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
