# Generated by Django 4.0.6 on 2022-08-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0004_empleados_delete_familia_alter_herramientas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientas',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
