# Generated by Django 4.0.6 on 2022-08-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0005_herramientas_disponible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herramientas',
            options={'ordering': ('nombre', 'tipo_de_tarea'), 'verbose_name': 'Herramienta', 'verbose_name_plural': 'Herramientas'},
        ),
        migrations.RemoveField(
            model_name='herramientas',
            name='responsable_de_uso',
        ),
        migrations.AlterField(
            model_name='tareas',
            name='dia_de_creacion',
            field=models.DateTimeField(),
        ),
    ]
